# Generated by Django 5.2.17 on 2026-09-02 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='General Merchandise', max_length=100)),
                ('unit_buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_glass_bottle', models.BooleanField(default=False)),
                ('bottles_per_unit', models.IntegerField(default=1)),
                ('bulk_min_qty', models.IntegerField(default=0)),
                ('bulk_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('reason', models.TextField(blank=True, default='')),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='inventory.product')),
            ],
            options={
                'db_table': 'damage_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('stock_in', 'Stock in'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damage', 'Damage')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'name'], name='products_workspa_e7dcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['workspace', '-created_at'], name='stock_trans_workspa_9f1ea5_idx'),
        ),
    ]
