# Generated by Django 5.2.17 on 2026-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='prescription_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'barcode'], name='products_workspa_8bd919_idx'),
        ),
    ]
