# Generated by Django 5.2.17 on 2026-09-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='access',
            field=models.CharField(choices=[('standard', 'Standard (trial, then pay)'), ('free', 'Free (no subscription needed)'), ('suspended', 'Suspended')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='access_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
